### ISSUE TITLE
Markdown translation Audit tasks

### ISSUE THREAD

**Issue by Malajab** [Malajab/incyber#10]
Here are all the Markdown translation audit tasks 

### Tasks list
- [x] Review Reconnaissance
- [x] Review Resource Development
- [ ] Review Initial Access
- [ ] Review Execution
- [ ] Review Persistence
- [ ] Review Privilege Escalation
- [ ] Review Defense Evasion
- [ ] Review Credential Access
- [ ] Review Discovery 
- [ ] Review Lateral Movement 
- [ ] Review Collection 
- [ ] Review Command and Control 
- [ ] Review Exfiltration
- [ ] Review Impact

**Comment by Malajab** [comment]
- Round one audit finish 
- Round two start assign to Salah Altokhais  & Fahad Alduraibi.
