### ISSUE TITLE
Markdown translation tasks

### ISSUE THREAD

**Issue by Malajab** [Malajab/incyber#9]
Here are all the Markdown translation tasks 

### Tasks list
- [x] Create Reconnaissance
- [x] Create Resource Development
- [x] Create Initial Access
- [x] Create Execution
- [x] Create Persistence
- [x] Create Privilege Escalation
- [x] Create Defense Evasion
- [x] Create Credential Access
- [x] Create Discovery 
- [x] Create Lateral Movement 
- [x] Create Collection 
- [x] Create Command and Control 
- [x] Create Exfiltration
- [x] Create Impact
